# Generated by Django 5.1.4 on 2025-01-07 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campapp', '0003_alter_user_stud_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='course',
            field=models.CharField(default='', max_length=100),
        ),
    ]
