# Generated by Django 5.1.4 on 2025-01-07 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campapp', '0004_alter_user_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
