# Generated by Django 5.1.4 on 2025-02-08 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campapp', '0008_question_explanation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizresult',
            old_name='business_score',
            new_name='Analytical_score',
        ),
        migrations.RenameField(
            model_name='quizresult',
            old_name='humanities_score',
            new_name='Numerical_score',
        ),
        migrations.RenameField(
            model_name='quizresult',
            old_name='law_score',
            new_name='Verbal_score',
        ),
        migrations.RemoveField(
            model_name='quizresult',
            name='media_score',
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('Verbal Ability', 'Verbal Ability'), ('Analytical Ability', 'Analytical Ability'), ('Numerical Ability', 'Numerical Ability')], max_length=20),
        ),
    ]
