# Generated by Django 5.1.4 on 2025-02-08 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campapp', '0009_rename_business_score_quizresult_analytical_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='question_images/'),
        ),
    ]
