# Generated by Django 5.1.4 on 2025-02-08 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campapp', '0010_question_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='course_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/question_images/'),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='recommended_course',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
