# Generated by Django 5.1.4 on 2025-02-09 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campapp', '0012_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='explanation',
        ),
    ]
