# Generated by Django 5.1.4 on 2025-02-13 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campapp', '0013_remove_question_explanation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='Courses',
        ),
    ]
