# Generated by Django 5.1.4 on 2025-02-13 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campapp', '0014_rename_course_courses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='college',
            old_name='ranking',
            new_name='nirf_ranking',
        ),
    ]
